<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>12.Promise的几个关键问题5</title>
</head>
<body>
<!--
问题产生：如果我们按照 4.3 的代码运行，假设第 2 次请求发送失败，那么会抛出一个 ERROR 错误
调用 reason => {} 失败的回调，但可惜的是我们并没有给失败的回调返回值，所以返回 undefined。
而 undefined 恰好是非 Promise 值，这导致在之后的请求中变为成功！这显然是不对的。

解决的问题：请求失败后就不再继续请求。
解决方法：为每一个失败的回调返回一个状态为 pending 的 Promise 实例。
-->
<script>
    //Promise如何串联多个一步任务？-------通过then链式调用
    function sendAjax(url, data) {
        return new Promise((resolve, reject) => {
            const xhr = new XMLHttpRequest()
            xhr.onreadystatechange = () => {
                if (xhr.readyState === 4) {
                    if (xhr.status >= 200 && xhr.status < 300) {
                        resolve(xhr.response)
                    } else {
                        reject('请求出问题了')
                    }
                }
            }
            //整理参数
            let str = ''
            for (let key in data) {
                str += `${key}=${data[key]}&`
            }
            str.slice(0, -1);

            xhr.open('GET', url + '?' + str)
            xhr.responseType = 'json'
            xhr.send()
        })
    }

    sendAjax('https://api.apiopen.top/api/getHaoKanVideo12', {
        page: '0',
        size: '2'
    }).then(
        value => {
            console.log('第一次请求成功', value);
            return sendAjax('https://api.apiopen.top/api/getHaoKanVideo', {
                page: '0',
                size: '2'
            })
        },
        reason => {
            console.log('第一次请求失败',reason);
            return new Promise(()=>{})}
    ).then(
        value => {
            console.log('第二次成功了', value);
            return sendAjax('https://api.apiopen.top/api/getHaoKanVideo', {
                page: '0',
                size: '2'
            })
        },
        reason => {
            console.log('第二次请求失败', reason);
            return new Promise(()=>{})
        }
    )
        .then(
            value => {
                console.log('第三次成功了', value);
                return sendAjax('https://api.apiopen.top/api/getHaoKanVideo', {
                    page: '0',
                    size: '2'
                })
            },
            reason => {
                console.log('第三次请求失败', reason)

            }
        )
</script>
</body>
</html>